export default function getInternalRepls()
{
    return [
        {
            "languages": [
                ".*"
            ],
            "patterns": [
                [
                    "[A-Z]{2}[a-z]+",
                    "$&",
                    "t",
                    "FIxes my HEavy SHift KEy"
                ],
                [
                    "([a-z])\\1{2,}",
                    "$1$1",
                    "igsp",
                    "tooo many"
                ]
            ]
        },
        {
            "languages": [
                "(java|type)script(react)?|c(pp|sharp)?|java"
            ],
            "patterns": [
                [
                    "pirate",
                    "private"
                ],
                [
                    "pubic",
                    "public"
                ],
                [
                    "c(nost|osnt|onts)",
                    "const"
                ]
            ]
        },
        {
            "languages": [
                "markdown|plaintext"
            ],
            "patterns": [
                [
                    "abuot",
                    "about",
                    "ip"
                ],
                [
                    "atfer",
                    "after",
                    "ip"
                ],
                [
                    "agian(st)?",
                    "again$1",
                    "ip"
                ],
                [
                    "aslo",
                    "also",
                    "ip"
                ],
                [
                    "([bnmst])a",
                    "a$1",
                    "ip"
                ],
                [
                    "([bcfghtw])([ai])l",
                    "$1$2ll",
                    "ip"
                ],
                [
                    "([kstw])il",
                    "$1ill",
                    "ip"
                ],
                [
                    "a([dty])n",
                    "an$1",
                    "ip"
                ],
                [
                    "e([bhw])",
                    "$1e",
                    "ip"
                ],
                [
                    "pu",
                    "up",
                    "ip"
                ],
                [
                    "(fro?|ofr|orf)",
                    "for",
                    "ip",
                    "i'm on the fence about including 'fro' as a mispelling"
                ],
                [
                    "ti(s)?",
                    "it$1",
                    "ip"
                ],
                [
                    "([fns])i",
                    "i$1",
                    "ip"
                ],
                [
                    "([fhnr])o",
                    "o$1",
                    "ip"
                ],
                [
                    "o([gst])",
                    "$1o",
                    "ip"
                ],
                [
                    "([bcr]a|(br|l|sp)i|[ms]e|scu)t(le|el)",
                    "$1ttle",
                    "ip"
                ],
                [
                    "(teh|hte|t[he])([my])?",
                    "the$2",
                    "ip"
                ],
                [
                    "lie([cfkmnv])",
                    "li$1e",
                    "ip"
                ],
                [
                    "(teh|hte|th)n",
                    "then",
                    "ip",
                    "Special case: 'ten' is a word"
                ],
                [
                    "([tw])h?ere?",
                    "$1here",
                    "ip"
                ],
                [
                    "([hmps])u",
                    "u$1",
                    "ip"
                ],
                [
                    "w(il|li)l?",
                    "will",
                    "ip"
                ],
                [
                    "w(ehn|hne)",
                    "when",
                    "ip"
                ]
            ]
        }
    ];
}